- name: install debian packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - screen
    - nano
  when: ansible_os_family == "Debian"

- name: install freebsd packages
  pkgng: name={{ item }} state=present
  with_items:
    - screen
    - nano
  when: ansible_os_family == "FreeBSD"

- name: "adding bashrc"
  copy: src=/home/ansible/bash.bashrc dest=/home/ansible/bash.bashrc owner=ansible group=ansible mode=0644
